### ISSUE TITLE
HasParameterisedEnumerator

### ISSUE THREAD

**Issue by delicious-lemon** [mlabs-haskell/apropos-tx#17]
Sometimes we will want to model something that can easily be exhaustively enumerated. We want to avoid generating repeat tests so perhaps we can handle this with another class - `HasParameterisedEnumerator`

**Comment by delicious-lemon** [comment]
Since we have our own `Gen` abstraction layer now we can interpret it as an enumerator.

https://github.com/mlabs-haskell/apropos-tx/blob/main/src/Apropos/Gen/Enumerate.hs

**Comment by AriFordsham** [comment]
Enumerators are not on the roadmap right now.
