### ISSUE TITLE
Cleanliness and standards compliance

### ISSUE THREAD

**Issue by kozross** [mlabs-haskell/apropos-tx#2]
The code so far needs to be brought in-line with [our code style](https://github.com/mlabs-haskell/styleguide). This includes, but is not limited to:

* Linting and formatting
* Removing unused modules
* Documentation

**Comment by delicious-lemon** [comment]
I would like a make file that gives us a `make format` command.

**Comment by delicious-lemon** [comment]
We have a `make format` command :rocket: and the green checkmarks
