### ISSUE TITLE
Proper type class either needs laws or removal

### ISSUE THREAD

**Issue by kozross** [mlabs-haskell/apropos-tx#4]
The current design with the `Proper` type class appears to be for generality. However, it's currently lawless, and I'm not completely clear what this generality gives us. Do we expect multiple different model types? If so, we need to put that type class on firm rails with laws; if not, this type class should be replaced by an (opaque) type and functions.

**Comment by delicious-lemon** [comment]
I've been thinking this too. I've thrown out the `Proper` type class completely in this PR https://github.com/mlabs-haskell/apropos-tx/pull/9.

The new design uses multiple type classes each with fewer responsibilities that compose. I think this is a better direction.
